In [1]:
import numpy as np

In [25]:
def custom_vander(inp_arr,exp,increasing=False):
    #transpose the matrix
    arr_T=inp_arr.reshape(1,inp_arr.shape[0]).transpose()
    #set values in case of decreasing
    start,step,end=exp,-1,0  
    #set values in case of decreasing
    if increasing:
        start,step,end=1,1,exp+1
    #set first value in out_result
    out_result=arr_T**start
    #now skip first iteration, hence start+step
    for i in range(start+step,end,step):
        out_result=np.concatenate((out_result,arr_T**i),axis=1)
    return out_result

In [30]:
arr=np.array([1,2,4,5])
N=3
print("Input Array is :\n",arr)
print("Vander matrix in increasing order where N=",N,":\n",custom_vander(arr,3,increasing=True))
print("Vander matrix in decreasing order where N=",N,":\n",custom_vander(arr,3,increasing=False))


Input Array is :
 [1 2 4 5]
Vander matrix in increasing order where N= 3 :
 [[  1   1   1]
 [  2   4   8]
 [  4  16  64]
 [  5  25 125]]
Vander matrix in decreasing order where N= 3 :
 [[  1   1   1]
 [  8   4   2]
 [ 64  16   4]
 [125  25   5]]
